# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: solutionloft
          POSTGRES_DB: solutionloft
          POSTGRES_PASSWORD: ""

      - image: redis

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --pep8 --flake8

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy-to-development:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Deploy to EB
          command: |
            sudo pip install awsebcli --upgrade
            eb init "Strand API" -r us-east-1 -p "arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running on 64bit Amazon Linux/2.6.4"
            echo "Initialized"
            eb use api-development
            echo "Used"
            eb deploy


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build

      - hold-for-development:
          type: approval
          requires:
           - build

      - deploy-to-development:
          requires:
            - hold-for-development
